services:
  iris-test:
    build: 
      args:
        IMAGE: ${IMAGE_IRIS_DEV_EM}
      context: iris-test
    image: iris-test  
    restart: always
    hostname: iris-test
    container_name: iris-test
    # command: -b /code/init_pyprod.sh
    environment:
      - TZ=$TZ
      - ISC_DATA_DIRECTORY=/databases
      - ISC_CPF_MERGE_FILE=/merge.cpf
      - PYTHONPATH=/usr/irissys/lib/python:/usr/irissys/mgr/python
    ports: 
      - 10972:1972
      - 10773:52773
      - 29001:29001
    volumes:
      - ./iris-test/src/code:/code
      - ./iris-test/src:/src
      - ./jdbc:/jdbc
      - databases_test:/databases
      - journal_test:/journal
      - journal2_test:/journal2
      - WIJ_test:/WIJ
      - ./merge.cpf:/merge.cpf
      - ./data:/data
    healthcheck:
      test: ["CMD", "iris", "session", "iris", "-U", "%SYS", "##class(%SYSTEM.OBJ).ShowClasses()"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
  jupyter:
    build: 
      context: jupyter
    restart: always
    hostname: jupyter
    environment:
      ISC_TEST_HOSTNAME: iris-test
      ISC_TEST_PORT: 1972
      ISC_TEST_NAMESPACE: USER
      ISC_TEST_USER: _SYSTEM
      ISC_TEST_PASSWORD: SYS
    ports:
      - 18888:8888
  postgres:
    container_name: test-postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgreSQL:/docker-entrypoint-initdb.d/
      - postgres-data_test:/var/lib/postgresql/data
    ports:
      - 52005:5432
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 30s
        timeout: 30s
        retries: 3


       
  mssql:
    build:
      args:
        IMAGE: mcr.microsoft.com/mssql/server:latest
      context: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - 1433:1433
    restart: unless-stopped
    container_name: test-mssql
    volumes:
      - mssql-data_test:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s

volumes:
  databases_test:
    external: true
    name: ${VOLUME_NAME}databases_test
  journal_test:
    external: true
    name: ${VOLUME_NAME}journal_test
  journal2_test:
    external: true
    name: ${VOLUME_NAME}journal2_test
  WIJ_test:
    external: true
    name: ${VOLUME_NAME}WIJ_test  
  mssql-data_test:
  postgres-data_test: