    zn "USER"
    set r=##class(%Net.HttpRequest).%New(),r.Server="pm.community.intersystems.com",r.SSLConfiguration="ISC.FeatureTracker.SSL.Config" d r.Get("/packages/zpm/latest/installer"),$system.OBJ.LoadStream(r.HttpResponse.Data,"c")
    zpm "repo -r -n registry -reset-defaults"
    zpm "install webterminal"
    zpm "enable -map -globally"
  
    zn "IRISAPP"
    set sc = $SYSTEM.OBJ.Import("/home/irisowner/dev/src","ck")
    do ##class(EnsLib.HL7.SchemaXML).Import("/home/irisowner/dev/src/HL7v2/HL7v25IHE.HL7")
    do ##class(EnsLib.HL7.SchemaXML).Import("/home/irisowner/dev/src/HL7v2/nonIHE.HL7")
    do ##class("Ens.Director").SetAutoStart("IRISAPP.prod.test", 0)
    do ##class(EnsLib.SQL.InboundAdapter).SetPersistentValue("get commandes from MSSQL","montant",200)
    do ##class(EnsLib.SQL.InboundAdapter).SetPersistentValue("get commandes from MSSQL","status","Completed")

    set ^Ens.Config.DefaultSettingsD("*","Demo.Temperature.TemperatureService","*","ArchiveIO") = $lb(1,"",0)
    set ^Ens.Config.DefaultSettingsD("*","Demo.Temperature.TemperatureService","*","CallInterval") = $lb("3600","",0)

    zn "%SYS"
    Do ##class(Security.Users).UnExpireUserPasswords("*")

    set SQLGateway = ##class(%SQLConnection).%New()
    set SQLGateway.Name = "iris"
    set SQLGateway.isJDBC = 1
    set SQLGateway.driver = "com.intersystems.jdbc.IRISDriver"
    set SQLGateway.URL = "jdbc:IRIS://host.docker.internal:11972/IRISAPP"
    set SQLGateway.classpath = "/jdbc/intersystems-jdbc-3.10.5.jar"
    set SQLGateway.Usr = "_SYSTEM"
    set SQLGateway.pwd = "SYS"
    set sc = SQLGateway.%Save()

    set SQLGateway = ##class(%SQLConnection).%New()
    set SQLGateway.Name = "mysql"
    set SQLGateway.isJDBC = 1
    set SQLGateway.driver = "com.mysql.cj.jdbc.Driver"
    set SQLGateway.URL = "jdbc:mysql://host.docker.internal:3306/formation"
    set SQLGateway.classpath = "/jdbc/mysql-connector-java-8.0.26.jar"
    set SQLGateway.Usr = "formation"
    set SQLGateway.pwd = "formation"
    set sc = SQLGateway.%Save()

    set SQLGateway = ##class(%SQLConnection).%New()
    set SQLGateway.Name = "oracle"
    set SQLGateway.isJDBC = 1
    set SQLGateway.driver = "oracle.jdbc.driver.OracleDriver"
    set SQLGateway.URL = "jdbc:oracle:thin:@host.docker.internal:1521:orcl"
    set SQLGateway.classpath = "/jdbc/ojdbc11.jar"
    set SQLGateway.Usr = "oracle"
    set SQLGateway.pwd = "oracle"
    set sc = SQLGateway.%Save()

    set SQLGateway = ##class(%SQLConnection).%New()
    set SQLGateway.Name = "mssql"
    set SQLGateway.isJDBC = 1
    set SQLGateway.driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    set SQLGateway.URL = "jdbc:sqlserver://mssql:1433;databaseName=master;encrypt=false"
    set SQLGateway.classpath = "/jdbc/mssql-jdbc-13.2.1.jre11.jar"
    set SQLGateway.Usr = "sa"
    set SQLGateway.pwd = "YourStrong!Passw0rd"
    set sc = SQLGateway.%Save()

    set SQLGateway = ##class(%SQLConnection).%New()
    set SQLGateway.Name = "postgres"
    set SQLGateway.isJDBC = 1
    set SQLGateway.driver = "org.postgresql.Driver"
    set SQLGateway.URL = "jdbc:postgresql://host.docker.internal:52004/postgres"
    set SQLGateway.classpath = "/jdbc/postgresql-42.6.0.jar"
    set SQLGateway.Usr = "postgres"
    set SQLGateway.pwd = "postgres"
    set sc = SQLGateway.%Save()   

    // Modifiy /terminalsocket application to allow WebTerminal to work with %AdminSecure privilege

    set app = ##class(Security.Applications).%OpenId("/terminalsocket")
    do app.MatchRoles.Clear()
    do app.MatchRoles.Insert(":%DB_IRISSYS:%DB_USER:WebTerminal")
    set sc = app.%Save()

    set role = ##class(Security.Roles).%OpenId("webterminal")
    set resource = ##class(Security.Resource).%New()
    set resource.Name = "%Admin_Secure"
    set resource.Permission = 4
    do role.Resources.Insert(resource)
    set sc = role.%Save()

    halt
