Class Tutorial.ExampleProduction Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="Tutorial.ExampleProduction" TestingEnabled="true" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="Tutorial.ExampleOperation" Category="" ClassName="Tutorial.ExampleOperation" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
